### ISSUE TITLE
Default values to variables

### ISSUE THREAD

**Issue by Vadiok** [torch2424/sass-bem-mixins#1]
Please, add the ``!default`` keyword to $elementSeparator & $modifierSeparator variables.
https://sass-lang.com/documentation/variables#default-values

**Comment by torch2424** [comment]
@Vadiok 

Hello! Thanks for the issue! :tada:  

So I haven't worked on this project in a super long time, and I don't have much time with all of my other work that I do :sob:  

Would you be open to creating a PR for this? Would be happy to review it! :smile:

**Comment by torch2424** [comment]
Published in 1.1.7 :smile: https://unpkg.com/browse/sass-bem-mixins@1.1.7/

Thanks for the PR at #1 @Vadiok :smile: :+1:

**Comment by Vadiok** [comment]
Thank you for package.
